### ISSUE TITLE
input-flow doesn't work with simple arrays

### ISSUE THREAD

**Issue by thetric** [jeysal/ngx-input-flow#11] opened 2017-09-01 09:11 UTC
ngx-input-flow works flawless when using it with arrays of objects. But if I use an array of strings, input-flow adds new components for every keystroke:

![screenshot_2017-09-01_11-05-55](https://user-images.githubusercontent.com/19861998/29963066-d5607da6-8f05-11e7-8df4-98cd45192f66.png)

Here's the code to reproduce this:
```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  todos = ['Implement a feature', 'Fix bugs', 'Publish a new release'];
}
```

```html
<section [(ngxInputFlow)]="todos" #input="ngxInputFlow">
  <div *ngFor="let todo of input.flow(); let i = index" [ngxInputFlowModel]="todo">
    <input type="text" [(ngModel)]="todos[i]" name="todo">
  </div>
</section>
```

**Comment by jeysal** [comment] 2017-09-01 09:40
Thanks for reporting, I'll try to reproduce as soon as I can, which will unfortunately be a few weeks from now since I don't have access to my computer at the moment.

**Comment by jeysal** [comment] 2017-09-18 17:32
I'm pretty sure this is caused by `ngModel` reassigning the flow item (the last displayed item that is not part of the actual array of elements).
I don't think we can easily support the use case where this assignment is performed.

Also, I don't think it is a good idea to use an array of strings and then bind to `ngModel` like this. If you eliminate `ngx-input-flow` from this example and try to change one of the strings, you will notice that after each key press, the input field loses focus. In this case, it would make more sense to use an array of objects with a single string property.

**Closed as completed by jeysal** 2017-09-18 17:32 UTC
